### ISSUE TITLE
[XY Plot Time Series] - Various Fixes

### ISSUE THREAD

**Issue by albertodainotti** [CAIDA/ioda-ui#187]
- [x] zoom misbehaves when dragging beyond end of graph
- [x] lines are showing points also when data is NULL/missing (e.g., towards the end of the graph)
  - it only happens at the normalized graph
- [x] colors of each of IBR, BGP, AP should always be the same: red for IBR, green for BGP, blue for AP 
- [x] buttons for zoom overlap over data displayed on visual. It should be above so that the data isn’t hidden underneath the buttons.
<img width="350" alt="Screen Shot 2021-05-06 at 11 05 38 AM" src="https://user-images.githubusercontent.com/30266581/117350235-2de56080-ae61-11eb-8746-e269d7388720.png">

**Comment by JayWebz** [comment]
* The first issue - zooming beyond the edge of the chart is issue addressed on their forum https://canvasjs.com/forums/topic/problem-zooming-to-the-end-of-a-chart/. It seems that they do not consider it an issue with priority enough to update yet. 
* The current solution is to hold down the mouse and continue trying to line up the zoom with the edge of the chart as the selection is still active
* Found another solution https://canvasjs.com/forums/topic/hard-to-zoom-around-corners-of-graph/ that allows me to add padding to the edge of the chart.
* Added 5% of timespan as additional x-axis space so that zooming at the most recent time stamp isn’t as tough to get to the end of. Easy enough to increase/decrease as needed.

**Comment by JayWebz** [comment]
example of null data fix - https://dev.v2.ioda.caida.org/country/IT?from=1621036800&until=1621123199, BGP at 4:05a
